# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jonasito\Desktop\pythonProject\Ultimo proyecto al 06082021\ProjectosPython\Pro-pqt5\nume.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogPrinc(object):
    def setupUi(self, DialogPrinc):
        DialogPrinc.setObjectName("DialogPrinc")
        DialogPrinc.resize(400, 300)
        self.BotonPersonas = QtWidgets.QPushButton(DialogPrinc)
        self.BotonPersonas.setGeometry(QtCore.QRect(260, 60, 121, 41))
        self.BotonPersonas.setObjectName("BotonPersonas")
        self.BotonProductos = QtWidgets.QPushButton(DialogPrinc)
        self.BotonProductos.setGeometry(QtCore.QRect(260, 130, 121, 41))
        self.BotonProductos.setObjectName("BotonProductos")
        self.pushButton = QtWidgets.QPushButton(DialogPrinc)
        self.pushButton.setGeometry(QtCore.QRect(260, 200, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(DialogPrinc)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 250, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.LabelTitulo = QtWidgets.QLabel(DialogPrinc)
        self.LabelTitulo.setGeometry(QtCore.QRect(20, 10, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LabelTitulo.setFont(font)
        self.LabelTitulo.setObjectName("LabelTitulo")

        self.retranslateUi(DialogPrinc)
        QtCore.QMetaObject.connectSlotsByName(DialogPrinc)

    def retranslateUi(self, DialogPrinc):
        _translate = QtCore.QCoreApplication.translate
        DialogPrinc.setWindowTitle(_translate("DialogPrinc", "Menucito"))
        self.BotonPersonas.setText(_translate("DialogPrinc", "Personas"))
        self.BotonProductos.setText(_translate("DialogPrinc", "Productos"))
        self.pushButton.setText(_translate("DialogPrinc", "Reporte"))
        self.pushButton_2.setText(_translate("DialogPrinc", "Salir"))
        self.LabelTitulo.setText(_translate("DialogPrinc", "Ingreso de informacion"))
