# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Desktop\Python\ProjectosPython\Pro-pqt5\ventanavista.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 529)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\User\\Desktop\\Python\\ProjectosPython\\Pro-pqt5\\../../../../Pictures/820baa4c62bd9426d3d190524b4183b3--presentation-templates-business-management.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(4.0)
        MainWindow.setStyleSheet("background-color: rgb(130, 255, 199);\n"
"color: rgb(71, 10, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(610, 10, 75, 23))
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnModificar = QtWidgets.QPushButton(self.centralwidget)
        self.btnModificar.setGeometry(QtCore.QRect(610, 50, 75, 23))
        self.btnModificar.setObjectName("btnModificar")
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(610, 90, 75, 23))
        self.btnEliminar.setObjectName("btnEliminar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(610, 130, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        self.tblContactos = QtWidgets.QTableWidget(self.centralwidget)
        self.tblContactos.setGeometry(QtCore.QRect(10, 230, 701, 211))
        self.tblContactos.setRowCount(1)
        self.tblContactos.setColumnCount(5)
        self.tblContactos.setObjectName("tblContactos")
        self.txtProducto = QtWidgets.QLineEdit(self.centralwidget)
        self.txtProducto.setGeometry(QtCore.QRect(30, 80, 171, 20))
        self.txtProducto.setObjectName("txtProducto")
        self.txtCantidad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCantidad.setGeometry(QtCore.QRect(270, 80, 161, 20))
        self.txtCantidad.setObjectName("txtCantidad")
        self.txtCodigo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCodigo.setGeometry(QtCore.QRect(30, 30, 171, 20))
        self.txtCodigo.setObjectName("txtCodigo")
        self.txtValor = QtWidgets.QLineEdit(self.centralwidget)
        self.txtValor.setGeometry(QtCore.QRect(30, 130, 171, 20))
        self.txtValor.setObjectName("txtValor")
        self.txtCed = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCed.setGeometry(QtCore.QRect(270, 130, 161, 20))
        self.txtCed.setObjectName("txtCed")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 60, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 110, 47, 13))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contactos"))
        self.btnAgregar.setText(_translate("MainWindow", "Agregar"))
        self.btnModificar.setText(_translate("MainWindow", "Modificar"))
        self.btnEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.label.setText(_translate("MainWindow", "Codigo Producto"))
        self.label_2.setText(_translate("MainWindow", "Producto"))
        self.label_3.setText(_translate("MainWindow", "Cantidad"))
        self.label_4.setText(_translate("MainWindow", "Valor"))
        self.label_5.setText(_translate("MainWindow", "Cedula"))
